SET IDENTITY_INSERT [dbo].[Pokemon] ON
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (1, 'bulbasaur', 'ivysaur', '16', 'grass', 'poison')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (2, 'ivysaur', 'venusaur', '32', 'grass', 'poison')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (3, 'venusaur', null, null, 'grass', 'poison')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (4, 'charmander', 'charmeleon', '16', 'fire', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (5, 'charmeleon', 'charizard', '36', 'fire', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (6, 'charizard', null, null, 'fire', 'flying')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (7, 'squirtle', 'wartortle', '16', 'water', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (8, 'wartortle', 'blastoise', '36', 'water', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (9, 'blastoise', null, null, 'water', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (10, 'caterpie', 'metapod', '7', 'bug', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (11, 'metapod', 'butterfree', '10', 'bug', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (12, 'butterfree', null, null, 'bug', 'flying')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (13, 'weedle', 'kakuna', '7', 'bug', 'poison')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (14, 'kakuna', 'beedrill', '10', 'bug', 'poison')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (15, 'beedrill', null, null, 'bug', 'poison')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (16, 'pidgey', 'pidgeotto', '18', 'normal', 'flying')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (17, 'pidgeotto', 'pidgeot', '36', 'normal', 'flying')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (18, 'pidgeot', null, null, 'normal', 'flying')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (19, 'rattata', 'raticate', '20', 'normal', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (20, 'raticate', null, null, 'normal', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (21, 'spearow', 'fearow', '20', 'normal', 'flying')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (22, 'fearow', null, null, 'normal', 'flying')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (23, 'ekans', 'arbok', 'thunder stone', 'poison', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (24, 'arbok', null, null, 'poison', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (25, 'pikachu', 'raichu', null, 'electric', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (26, 'raichu', null, null, 'electric', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (27, 'sandshrew', 'sandslash', '22', 'ground', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (28, 'sandslash', null, null, 'ground', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (29, 'nidoran-f', 'nidorina', '16', 'poison', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (30, 'nidorina', 'nidoqueen', 'moon stone', 'poison', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (31, 'nidoqueen', null, null, 'poison', 'ground')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (32, 'nidoran-m', 'nidorino', '16', 'poison', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (33, 'nidorino', 'nidoking', 'moon stone', 'poison', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (34, 'nidoking', null, null, 'poison', 'ground')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (35, 'clefairy', 'clefable', 'moon stone', 'fairy', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (36, 'clefable', null, null, 'fairy', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (37, 'vulpix', 'ninetales', 'fire stone', 'fire', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (38, 'ninetales', null, null, 'fire', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (39, 'jigglypuff', 'wigglytuff', 'moon stone', 'normal', 'fairy')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (40, 'wigglytuff', null, null, 'normal', 'fairy')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (41, 'zubat', 'golbat', '22', 'poison', 'flying')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (42, 'golbat', null, null, 'poison', 'flying')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (43, 'oddish', 'gloom', '21', 'grass', 'poison')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (44, 'gloom', 'vileplume', 'leaf stone', 'grass', 'poison')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (45, 'vileplume', null, null, 'grass', 'poison')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (46, 'paras', 'parasect', '24', 'bug', 'grass')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (47, 'parasect', null, null, 'bug', 'grass')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (48, 'venonat', 'venomoth', '31', 'bug', 'poison')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (49, 'venomoth', null, null, 'bug', 'poison')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (50, 'diglett', 'dugtrio', '26', 'ground', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (51, 'dugtrio', null, null, 'ground', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (52, 'meowth', 'persian', '28', 'normal', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (53, 'persian', null, null, 'normal', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (54, 'psyduck', 'golduck', '33', 'water', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (55, 'golduck', null, null, 'water', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (56, 'mankey', 'primeape', '28', 'fighting', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (57, 'primeape', null, null, 'fighting', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (58, 'growlithe', 'arcanine', 'fire stone', 'fire', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (59, 'arcanine', null, null, 'fire', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (60, 'poliwag', 'poliwhirl', '25', 'water', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (61, 'poliwhirl', 'poliwrath', 'water stone', 'water', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (62, 'poliwrath', null, null, 'water', 'fighting')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (63, 'abra', 'kadabra', '16', 'psychic', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (64, 'kadabra', 'alakazam', 'trade', 'psychic', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (65, 'alakazam', null, null, 'psychic', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (66, 'machop', 'machoke', '28', 'fighting', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (67, 'machoke', 'machamp', 'trade', 'fighting', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (68, 'machamp', null, null, 'fighting', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (69, 'bellsprout', 'weepinbell', '21', 'grass', 'poison')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (70, 'weepinbell', 'victreebel', 'leaf stone', 'grass', 'poison')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (71, 'victreebel', null, null, 'grass', 'poison')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (72, 'tentacool', 'tentacruel', '30', 'water', 'poison')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (73, 'tentacruel', null, null, 'water', 'poison')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (74, 'geodude', 'graveler', '25', 'rock', 'ground')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (75, 'graveler', 'golem', 'trade', 'rock', 'ground')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (76, 'golem', null, null, 'rock', 'ground')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (77, 'ponyta', 'rapidash', '40', 'fire', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (78, 'rapidash', null, null, 'fire', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (79, 'slowpoke', 'slowbro', '37', 'water', 'psychic')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (80, 'slowbro', null, null, 'water', 'psychic')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (81, 'magnemite', 'magneton', '30', 'electric', 'steel')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (82, 'magneton', null, null, 'electric', 'steel')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (83, 'farfetchd', null, null, 'normal', 'flying')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (84, 'doduo', 'dodrio', '31', 'normal', 'flying')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (85, 'dodrio', null, null, 'normal', 'flying')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (86, 'seel', 'dewgong', '34', 'water', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (87, 'dewgong', null, null, 'water', 'ice')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (88, 'grimer', 'muk', '38', 'poison', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (89, 'muk', null, null, 'poison', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (90, 'shellder', 'cloyster', 'water stone', 'water', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (91, 'cloyster', null, null, 'water', 'ice')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (92, 'gastly', 'haunter', '25', 'ghost', 'poison')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (93, 'haunter', 'gengar', 'trade', 'ghost', 'poison')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (94, 'gengar', null, null, 'ghost', 'poison')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (95, 'onix', null, null, 'rock', 'ground')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (96, 'drowzee', 'hypno', '26', 'psychic', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (97, 'hypno', null, null, 'psychic', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (98, 'krabby', 'kingler', '28', 'water', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (99, 'kingler', null, null, 'water', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (100, 'voltorb', 'electrode', '30', 'electric', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (101, 'electrode', null, null, 'electric', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (102, 'exeggcute', 'exeggutor', 'leaf stone', 'grass', 'psychic')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (103, 'exeggutor', null, null, 'grass', 'psychic')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (104, 'cubone', 'marowak', '28', 'ground', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (105, 'marowak', null, null, 'ground', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (106, 'hitmonlee', null, null, 'fighting', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (107, 'hitmonchan', null, null, 'fighting', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (108, 'lickitung', null, null, 'normal', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (109, 'koffing', 'weezing', '35', 'poison', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (110, 'weezing', null, null, 'poison', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (111, 'rhyhorn', 'rhydon', '42', 'ground', 'rock')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (112, 'rhydon', null, null, 'ground', 'rock')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (113, 'chansey', null, null, 'normal', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (114, 'tangela', null, null, 'grass', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (115, 'kangaskhan', null, null, 'normal', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (116, 'horsea', 'seadra', '32', 'water', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (117, 'seadra', null, null, 'water', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (118, 'goldeen', 'seaking', '33', 'water', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (119, 'seaking', null, null, 'water', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (120, 'staryu', 'starmie', 'water stone', 'water', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (121, 'starmie', null, null, 'water', 'psychic')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (122, 'mr-mime', null, null, 'psychic', 'fairy')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (123, 'scyther', null, null, 'bug', 'flying')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (124, 'jynx', null, null, 'ice', 'psychic')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (125, 'electabuzz', null, null, 'electric', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (126, 'magmar', null, null, 'fire', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (127, 'pinsir', null, null, 'bug', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (128, 'tauros', null, null, 'normal', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (129, 'magikarp', 'gyarados', '20', 'water', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (130, 'gyarados', null, null, 'water', 'flying')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (131, 'lapras', null, null, 'water', 'ice')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (132, 'ditto', null, null, 'normal', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (133, 'eevee', null, null, 'normal', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (134, 'vaporeon', null, null, 'water', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (135, 'jolteon', null, null, 'electric', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (136, 'flareon', null, null, 'fire', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (137, 'porygon', null, null, 'normal', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (138, 'omanyte', 'omastar', '40', 'rock', 'water')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (139, 'omastar', null, null, 'rock', 'water')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (140, 'kabuto', 'kabutops', '40', 'rock', 'water')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (141, 'kabutops', null, null, 'rock', 'water')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (142, 'aerodactyl', null, null, 'rock', 'flying')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (143, 'snorlax', null, null, 'normal', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (144, 'articuno', null, null, 'ice', 'flying')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (145, 'zapdos', null, null, 'electric', 'flying')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (146, 'moltres', null, null, 'fire', 'flying')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (147, 'dratini', 'dragonair', '30', 'dragon', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (148, 'dragonair', 'dragonite', '55', 'dragon', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (149, 'dragonite', null, null, 'dragon', 'flying')
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (150, 'mewtwo', null, null, 'psychic', null)
INSERT INTO [dbo].[Pokemon] ([PokemonId], [Name], [EvolutionName], [EvolutionMethod], [Type1], [Type2]) VALUES (151, 'mew', null, null, 'psychic', null)
SET IDENTITY_INSERT [dbo].[Pokemon] OFF